# Cau hinh Database
db.url=jdbc:oracle:thin:@localhost:1521:orcl
db.username=system
db.password=123456
db.driver=oracle.jdbc.driver.OracleDriver

# Cau hinh ung dung
app.name=Java Database Program
app.version=1.0
